---
title: "About"
toc: false
---
# About
::: {.main-text}
The Maritime Refrigeration Technology Hub is established as a response to the need for intensified knowledge transfer and information distribution regarding utilization of more climate friendly solutions to heating and cooling onboard maritime vessels.
The widespread usage of the refrigerant R-22 and the expected transition from hydrochlorofluorocarbons (HCFC) to hydrofluorocarbon (HFC) in the HVAC&R (Heating, Ventilating and Air Conditioning & Refrigeration) systems of marine vessels was directly mentioned during the talks leading to the decision in Kigali, Rwanda, where the global phase down of HFCs was decided at the 28th Meeting of the Parties under the Montreal Protocol (Oct. 2016).

Due to the harsh physical environment on marine vessels, the direct refrigerant emissions are often very high. According to the International Maritime Organisation the total use of HCFC/HFC as refrigerant in the world merchant fleet is estimated to consist of 70% R-22, 26% R-134a and 4% R-404A (IMO, 2014). The release of refrigerants from global shipping (refrigeration containers excluded) is estimated at 8,400 tonnes, which corresponds to around 15 million tonnes CO2 equivalent emissions. If these numbers are compared to the CO2 emissions of shipping, the refrigerant emissions constitute about 2% of the greenhouse gas (GHG) emissions of shipping.

Currently there is only scattered information available on how the maritime sector could leapfrog directly towards a refrigeration technology with a low environmental impact, and hence the intention of this web-based technology hub is to collect and disseminate information, experience and knowledge to accelerate this transition for the maritime sector.

The initiative for the hub is taken by Sintef Ocean, Sintef Energy Research and the Norwegian University of Science and Technology through the projects Coolfish and CruiZE.
:::